name: todo_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
   sdk: '>=3.2.0 <4.0.0'

dependencies:
   flutter:
      sdk: flutter
   implicitly_animated_list: ^2.2.0
   moor_flutter: ^4.0.0
   provider: ^6.1.1
   shared_preferences: ^2.2.2

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^3.0.1
   build_runner: ^2.4.7
   moor_generator: ^4.4.1

flutter:
   uses-material-design: true
